INSERT INTO tb_equipment (model) VALUES ('Alcatel 1662');
INSERT INTO tb_equipment (model) VALUES ('Lucent ADMU');
INSERT INTO tb_equipment (model) VALUES ('Marconi 1664');
INSERT INTO tb_equipment (model) VALUES ('Nokia 1830');
INSERT INTO tb_equipment (model) VALUES ('Padtec L6400');
INSERT INTO tb_equipment (model) VALUES ('Huawei 6800');
INSERT INTO tb_equipment (model) VALUES ('Ciena 6500');

INSERT INTO tb_card (model, feature, functionality, connection, reset_procedure, exchange_procedure, img_url) VALUES ('ISA ethernet 10G', 'Placa de 1 tributário ethernet de 10GB', 'Realiza analise de trafego ethernet no lado cliente e lado VCG', 'conecta a placa de agredado STM-64', 'Retirar do slot e aguardar 10 segundos para retornar, não há configuração para reset', 'Retirar a placa do slot e colocar a placa sobressalente, não há configuração para troca', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_card (model, feature, functionality, connection, reset_procedure, exchange_procedure, img_url) VALUES ('Loac', 'Placa amplificadora de entrada e saída', 'Consegue medir nível de potência de entrada e saída', 'conecta ao DGO ou a uma placa mux/demux', 'Retirar do slot e aguardar 10 segundos para retornar, não há configuração para reset', 'Retirar a placa do slot e colocar a placa sobressalente, não há configuração para troca', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_card (model, feature, functionality, connection, reset_procedure, exchange_procedure, img_url) VALUES ('Poac', 'Placa amplificadora de entrada', 'Consegue medir nível de potência de entrada', 'conecta ao DGO ou a uma placa mux/demux', 'Retirar do slot e aguardar 10 segundos para retornar, não há configuração para reset', 'Retirar a placa do slot e colocar a placa sobressalente, não há configuração para troca', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_card (model, feature, functionality, connection, reset_procedure, exchange_procedure, img_url) VALUES ('Boac', 'Placa amplificadora de saída', 'Consegue medir nível de saída', 'conecta ao DGO ou a uma placa mux/demux', 'Retirar do slot e aguardar 10 segundos para retornar, não há configuração para reset', 'Retirar a placa do slot e colocar a placa sobressalente, não há configuração para troca', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_card (model, feature, functionality, connection, reset_procedure, exchange_procedure, img_url) VALUES ('Transponder 100GB', 'Placa que possui capacidade de ter sinal de 100GB no lado rede', 'Consegue medir potência de entrada e saida e efetuar perfomance', 'conecta ao DGO ou a uma placa mux/demux', 'Retirar do slot e aguardar 10 segundos para retornar, não há configuração para reset', 'Retirar a placa do slot e colocar a placa sobressalente, não há configuração para troca', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_card (model, feature, functionality, connection, reset_procedure, exchange_procedure, img_url) VALUES ('Amplificadora PSS32', 'Placa amplificadora de entrada', 'Consegue medir nível de potência de entrada', 'conecta ao DGO ou a uma placa mux/demux', 'Retirar do slot e aguardar 10 segundos para retornar, não há configuração para reset', 'Retirar a placa do slot e colocar a placa sobressalente, não há configuração para troca', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_card (model, feature, functionality, connection, reset_procedure, exchange_procedure, img_url) VALUES ('ISA ethernet 1G', 'Placa de vários tributário ethernet cpm saída de 1GB', 'Realiza analise de trafego ethernet no lado cliente e lado VCG', 'conecta a placa de agredado STM-64', 'Retirar do slot e aguardar 10 segundos para retornar, não há configuração para reset', 'Retirar a placa do slot e colocar a placa sobressalente, não há configuração para troca', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_card (model, feature, functionality, connection, reset_procedure, exchange_procedure, img_url) VALUES ('Amplificadora regeneradora PSS32', 'Placa amplificadora de entrada e saída', 'Consegue medir nível de potência de entrada e saída', 'conecta ao DGO ou a uma placa mux/demux', 'Retirar do slot e aguardar 10 segundos para retornar, não há configuração para reset', 'Retirar a placa do slot e colocar a placa sobressalente, não há configuração para troca', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_card (model, feature, functionality, connection, reset_procedure, exchange_procedure, img_url) VALUES ('Amplificadora PSS32 de RX', 'Placa amplificadora de entrada', 'Consegue medir nível de potência de entrada', 'conecta ao DGO ou a uma placa mux/demux', 'Retirar do slot e aguardar 10 segundos para retornar, não há configuração para reset', 'Retirar a placa do slot e colocar a placa sobressalente, não há configuração para troca', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_card (model, feature, functionality, connection, reset_procedure, exchange_procedure, img_url) VALUES ('Amplicadora PSS32 de TX', 'Placa amplificadora de saída', 'Consegue medir nível de saída', 'conecta ao DGO ou a uma placa mux/demux', 'Retirar do slot e aguardar 10 segundos para retornar, não há configuração para reset', 'Retirar a placa do slot e colocar a placa sobressalente, não há configuração para troca', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_card (model, feature, functionality, connection, reset_procedure, exchange_procedure, img_url) VALUES ('Transponder 10GB', 'Placa que possui capacidade de ter sinal de 10GB no lado rede', 'Consegue medir potência de entrada e saida e efetuar perfomance', 'conecta ao DGO ou a uma placa mux/demux', 'Retirar do slot e aguardar 10 segundos para retornar, não há configuração para reset', 'Retirar a placa do slot e colocar a placa sobressalente, não há configuração para troca', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_card (model, feature, functionality, connection, reset_procedure, exchange_procedure, img_url) VALUES ('Raman PSS32', 'Placa amplificadora de ganho Raman', 'Consegue medir nível de potência de entrada', 'conecta ao DGO ou a uma placa mux/demux', 'Retirar do slot e aguardar 10 segundos para retornar, não há configuração para reset', 'Retirar a placa do slot e colocar a placa sobressalente, não há configuração para troca', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_card (model, feature, functionality, connection, reset_procedure, exchange_procedure, img_url) VALUES ('Lucent ethernet 10GB', 'Placa de 1 tributário ethernet de 10GB', 'Realiza analise de trafego ethernet no lado cliente e lado VCG', 'conecta a placa de agredado STM-64', 'Retirar do slot e aguardar 10 segundos para retornar, não há configuração para reset', 'Retirar a placa do slot e colocar a placa sobressalente, não há configuração para troca', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_card (model, feature, functionality, connection, reset_procedure, exchange_procedure, img_url) VALUES ('CPL amplificadora regenerador', 'Placa amplificadora regeneradora de entrada e saída', 'Consegue medir nível de potência de entrada e saída', 'conecta ao DGO ou a uma placa mux/demux', 'Retirar do slot e aguardar 10 segundos para retornar, não há configuração para reset', 'Retirar a placa do slot e colocar a placa sobressalente, não há configuração para troca', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_card (model, feature, functionality, connection, reset_procedure, exchange_procedure, img_url) VALUES ('CPL RX', 'Placa amplificadora de entrada', 'Consegue medir nível de potência de entrada', 'conecta ao DGO ou a uma placa mux/demux', 'Retirar do slot e aguardar 10 segundos para retornar, não há configuração para reset', 'Retirar a placa do slot e colocar a placa sobressalente, não há configuração para troca', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_card (model, feature, functionality, connection, reset_procedure, exchange_procedure, img_url) VALUES ('CPL TX', 'Placa amplificadora de saída', 'Consegue medir nível de saída', 'conecta ao DGO ou a uma placa mux/demux', 'Retirar do slot e aguardar 10 segundos para retornar, não há configuração para reset', 'Retirar a placa do slot e colocar a placa sobressalente, não há configuração para troca', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_card (model, feature, functionality, connection, reset_procedure, exchange_procedure, img_url) VALUES ('Transponder 40GB', 'Placa que possui capacidade de ter sinal de 40GB no lado rede', 'Consegue medir potência de entrada e saida e efetuar perfomance', 'conecta ao DGO ou a uma placa mux/demux', 'Retirar do slot e aguardar 10 segundos para retornar, não há configuração para reset', 'Retirar a placa do slot e colocar a placa sobressalente, não há configuração para troca', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_card (model, feature, functionality, connection, reset_procedure, exchange_procedure, img_url) VALUES ('Amplificadora PSS16 RX', 'Placa amplificadora de entrada', 'Consegue medir nível de potência de entrada', 'conecta ao DGO ou a uma placa mux/demux', 'Retirar do slot e aguardar 10 segundos para retornar, não há configuração para reset', 'Retirar a placa do slot e colocar a placa sobressalente, não há configuração para troca', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_card (model, feature, functionality, connection, reset_procedure, exchange_procedure, img_url) VALUES ('ISA ethernet 100MB', 'Placa de vários tributário ethernet cpm saída de 100MB', 'Realiza analise de trafego ethernet no lado cliente e lado VCG', 'conecta a placa de agredado STM-64', 'Retirar do slot e aguardar 10 segundos para retornar, não há configuração para reset', 'Retirar a placa do slot e colocar a placa sobressalente, não há configuração para troca', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_card (model, feature, functionality, connection, reset_procedure, exchange_procedure, img_url) VALUES ('Amplificadora regeneradora PSS16', 'Placa amplificadora de entrada e saída', 'Consegue medir nível de potência de entrada e saída', 'conecta ao DGO ou a uma placa mux/demux', 'Retirar do slot e aguardar 10 segundos para retornar, não há configuração para reset', 'Retirar a placa do slot e colocar a placa sobressalente, não há configuração para troca', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_card (model, feature, functionality, connection, reset_procedure, exchange_procedure, img_url) VALUES ('Amplificadora PSS16 de RX', 'Placa amplificadora de entrada', 'Consegue medir nível de potência de entrada', 'conecta ao DGO ou a uma placa mux/demux', 'Retirar do slot e aguardar 10 segundos para retornar, não há configuração para reset', 'Retirar a placa do slot e colocar a placa sobressalente, não há configuração para troca', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_card (model, feature, functionality, connection, reset_procedure, exchange_procedure, img_url) VALUES ('Amplicadora PSS16 de TX', 'Placa amplificadora de saída', 'Consegue medir nível de saída', 'conecta ao DGO ou a uma placa mux/demux', 'Retirar do slot e aguardar 10 segundos para retornar, não há configuração para reset', 'Retirar a placa do slot e colocar a placa sobressalente, não há configuração para troca', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_card (model, feature, functionality, connection, reset_procedure, exchange_procedure, img_url) VALUES ('Transponder Muxponder 40GB', 'Placa que possui capacidade de ter sinal de 40GB no lado rede', 'Consegue medir potência de entrada e saida e efetuar perfomance', 'conecta ao DGO ou a uma placa mux/demux', 'Retirar do slot e aguardar 10 segundos para retornar, não há configuração para reset', 'Retirar a placa do slot e colocar a placa sobressalente, não há configuração para troca', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_card (model, feature, functionality, connection, reset_procedure, exchange_procedure, img_url) VALUES ('Raman PSS16', 'Placa amplificadora de ganho Raman', 'Consegue medir nível de potência de entrada', 'conecta ao DGO ou a uma placa mux/demux', 'Retirar do slot e aguardar 10 segundos para retornar, não há configuração para reset', 'Retirar a placa do slot e colocar a placa sobressalente, não há configuração para troca', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_card (model, feature, functionality, connection, reset_procedure, exchange_procedure, img_url) VALUES ('Synth16', 'Placa matriz e agregado STM-16', 'Realiza cross conection e perfomance STM-16', 'conexão via barramento interno do equipamento', 'Retirar do slot e aguardar 10 segundos para retornar, não há configuração para reset', 'Retirar a placa do slot, retirar a flash card dela e colocar na placa sobressalente, então conectar a placa sobressalente no slot', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_card (model, feature, functionality, connection, reset_procedure, exchange_procedure, img_url) VALUES ('Amplicadora TX/RX Huawei', 'Placa amplificadora de entrada e saída', 'Consegue medir nível de potência de entrada e saída', 'conecta ao DGO ou a uma placa mux/demux', 'Retirar do slot e aguardar 10 segundos para retornar, não há configuração para reset', 'Retirar a placa do slot e colocar a placa sobressalente, não há configuração para troca', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_card (model, feature, functionality, connection, reset_procedure, exchange_procedure, img_url) VALUES ('Amplificadora RX Huawei', 'Placa amplificadora de entrada', 'Consegue medir nível de potência de entrada', 'conecta ao DGO ou a uma placa mux/demux', 'Retirar do slot e aguardar 10 segundos para retornar, não há configuração para reset', 'Retirar a placa do slot e colocar a placa sobressalente, não há configuração para troca', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_card (model, feature, functionality, connection, reset_procedure, exchange_procedure, img_url) VALUES ('Amplificadora TX Huawei', 'Placa amplificadora de saída', 'Consegue medir nível de saída', 'conecta ao DGO ou a uma placa mux/demux', 'Retirar do slot e aguardar 10 segundos para retornar, não há configuração para reset', 'Retirar a placa do slot e colocar a placa sobressalente, não há configuração para troca', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_card (model, feature, functionality, connection, reset_procedure, exchange_procedure, img_url) VALUES ('Transponder 20GB', 'Placa que possui capacidade de ter sinal de 20GB no lado rede', 'Consegue medir potência de entrada e saida e efetuar perfomance', 'conecta ao DGO ou a uma placa mux/demux', 'Retirar do slot e aguardar 10 segundos para retornar, não há configuração para reset', 'Retirar a placa do slot e colocar a placa sobressalente, não há configuração para troca', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_card (model, feature, functionality, connection, reset_procedure, exchange_procedure, img_url) VALUES ('Amplificadora RX Ciena', 'Placa amplificadora de entrada', 'Consegue medir nível de potência de entrada', 'conecta ao DGO ou a uma placa mux/demux', 'Retirar do slot e aguardar 10 segundos para retornar, não há configuração para reset', 'Retirar a placa do slot e colocar a placa sobressalente, não há configuração para troca', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');


INSERT INTO tb_user (name, email, password) VALUES ('Axl', 'axl@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Rose', 'rose@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');

INSERT INTO tb_role (authority) VALUES ('ROLE_OPERATOR');
INSERT INTO tb_role (authority) VALUES ('ROLE_ADMIN');


